### PR TITLE
Add author fields

### PR DESCRIPTION
**Pull request by szabgab**
See also: https://pydigger.com/docs/author

### CODE REVIEW

**Comment by unnown** [comment]
Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
This will also ban the user for trying to abuse the system by doing marginal effort

**Comment by szabgab** [comment]
Wow, someone decided to spam GitHub. Several of my PRs got this comment (but none of the PRs that my projects received). Disregard it. Use your own judgement. I've reported this abuse to GitHub.

**Comment by unnown** [comment]
You reported yourself? good idea tbh

**Comment by smarie** [comment]
Thanks to both of you. In order to focus on more important topics and not to have to decide between one of you, I'll simply close this PR without merging. None of my python libraries has any "author" field set, and there are more than 20... One day maybe I'll fix this, thanks @szabgab for pointing out, I appreciate ! :)

**Pull request closed without merging**
